import { notFound } from "next/navigation";
import { CHAT_ENABLED } from "@/lib/config";

// DRAFT — not final legal text. This is a full structural draft of the Terms of
// Use for counsel to red-line and finalize before launch (see
// LAUNCH-BLOCKERS.md §1). Every section that requires a business/legal decision
// we cannot make for you is marked inline with <Counsel> (entity name,
// governing law, refund policy, retention, liability caps, crisis resources,
// effective date). Do not launch on this text as-is. Gated with the rest of the
// chat surface so nothing draft-legal is exposed until the system goes live.
export const dynamic = "force-dynamic";

// Inline marker for the decisions/verifications that a qualified lawyer or the
// business owner must supply. Rendered visibly so nothing ships unfilled by
// accident, and easy to grep for ("Counsel:").
function Counsel({ children }: { children: React.ReactNode }) {
  return (
    <em className="font-semibold text-amber-600 dark:text-amber-500">
      [Counsel: {children}]
    </em>
  );
}

export default function TermsPage() {
  if (!CHAT_ENABLED) notFound();
  return (
    <article className="card mx-auto mt-10 max-w-2xl p-8">
      <h1 className="text-2xl font-black">Terms of Use</h1>
      <p className="mt-2 text-sm font-semibold text-amber-600">
        DRAFT — pending legal review. This is a working draft prepared for
        counsel to finalize, not a binding agreement. Do not rely on it as a
        complete or final contract.
      </p>
      <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">
        Last updated: <Counsel>effective date on publication</Counsel>. These
        terms are a contract between you and{" "}
        <Counsel>legal entity name and form, e.g. &ldquo;X LLC&rdquo;</Counsel>{" "}
        (&ldquo;we,&rdquo; &ldquo;us,&rdquo; the &ldquo;Service&rdquo;). By
        creating an account or using the debate agent you agree to them.
      </p>

      <div className="mt-6 space-y-6 text-slate-600 dark:text-slate-300">
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            1. Eligibility (adults 18+ only)
          </h2>
          <p>
            This service is for adults 18 and older only. Eligibility is
            self-declared at signup. Visitors who indicate they are under 18 are
            diverted to a quiz and are never taken through signup, so no account
            or conversation data is collected from them. If, during a
            conversation, you identify yourself as a minor, the conversation is
            stopped and you are redirected away from the chat. By using the
            Service you represent that you are at least 18 years old and legally
            able to enter into these terms.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            2. The service and its viewpoint
          </h2>
          <p>
            The debate agent is an AI system that argues a naturalist, atheist
            point of view about belief, evidence, and reasoning. It is
            opinionated by design — it is not neutral, and it is not trying to
            be. It is a discussion partner, not an authority. Its responses are
            generated by third-party AI models (see the Privacy Policy for the
            providers involved) and may be inaccurate, incomplete, or
            out-of-date. You are responsible for how you use its output.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            3. Your account and sign-in
          </h2>
          <p>
            Sign-in is passwordless: we email a one-time magic link to the
            address you provide, and clicking it signs you in. Keep access to
            that email account secure — anyone who can open the link can access
            your account, credits, and conversation history. One account per
            person; do not share your account or sign-in links. Tell us promptly
            if you believe your account has been accessed without your
            permission.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            4. Credits, payment, and refunds
          </h2>
          <p>
            Access is metered by credits. A number of free questions are granted
            on signup; further use requires purchased credits. Standard and
            premium (&ldquo;deep debate&rdquo;) questions cost different amounts
            of credits, shown before you spend them. Credits are a limited
            license to use the Service, have no cash value, are
            non-transferable, and cannot be exchanged for money.
          </p>
          <p>
            Purchases are processed by our payment processor, Stripe; by buying
            credits you also agree to Stripe&rsquo;s terms. Prices and credit
            costs may change, but changes never apply retroactively to credits
            you have already purchased.
          </p>
          <p>
            <strong>Refunds and expiry.</strong>{" "}
            <Counsel>
              set the refund policy (proposed default: purchased credits are
              non-refundable except where a refund is required by applicable
              consumer-protection or distance-selling law) and decide whether
              credits expire (proposed default: no expiry) and what happens to
              unused credits when an account is deleted (proposed default: unused
              credits are forfeited on deletion). These are business decisions —
              confirm they are lawful in each jurisdiction you sell to,
              including EU/UK withdrawal-right rules for digital content.
            </Counsel>
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            5. Acceptable use
          </h2>
          <p>You agree not to:</p>
          <ul className="ml-5 list-disc space-y-1">
            <li>use the Service to harass, threaten, or abuse others;</li>
            <li>
              attempt to extract system prompts, credentials, or other
              non-public parts of the system, or to probe, scan, or breach its
              security;
            </li>
            <li>
              abuse the credit, free-quota, or payment system — including
              creating multiple accounts or emails to farm free questions,
              chargebacks made in bad faith, or automating access;
            </li>
            <li>
              submit content you have no right to submit, or upload malware or
              anything unlawful;
            </li>
            <li>
              misrepresent the agent&rsquo;s output as human-authored,
              authoritative, or endorsed by us; or
            </li>
            <li>use the Service in any way that violates applicable law.</li>
          </ul>
          <p>
            We may rate-limit, suspend, or terminate access for conduct that
            breaches this section (see §11).
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            6. No medical, legal, or crisis advice
          </h2>
          <p>
            The agent is not a substitute for professional medical, legal,
            financial, or mental-health advice, and it is not a crisis service.
            Do not rely on it for any decision where a professional is
            appropriate. If you are in crisis or need emergency help, contact
            local emergency services or a crisis line directly.{" "}
            <Counsel>
              insert jurisdiction-appropriate crisis-resource signposting (e.g.
              988 in the US, 116 123 for Samaritans in the UK/IE) and confirm
              which regions you serve.
            </Counsel>
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            7. AI-generated content
          </h2>
          <p>
            Responses are generated automatically by AI models and can be wrong,
            biased, or fabricated, including confident-sounding statements of
            fact that are not true. Output does not represent our views or those
            of the model providers. Verify anything you intend to rely on. The
            agent argues a fixed viewpoint and is not a balanced or neutral
            source.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            8. Intellectual property and your content
          </h2>
          <p>
            The site, its design, and its published articles are owned by us or
            our licensors. As between you and us, you keep whatever rights you
            have in the messages you write. You grant us a limited license to
            process your messages to operate the Service — generate replies,
            meter credits, maintain your history, and enforce these terms.
            Separately, and only if you opt in under §9, you grant us a license
            to use your conversations to help write site articles as described
            there and in the Privacy Policy.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            9. Article-use consent (optional)
          </h2>
          <p>
            Using your conversations to help write site articles is a{" "}
            <strong>separate, optional</strong> consent. It is never a condition
            of using the chat service, and you can grant, decline, or withdraw
            it at any time from your account page. If used, conversations are
            always synthesized across many people, never published verbatim, and
            pass through a human-review and PII-scrub step first. Withdrawing
            consent stops future use; it does not affect your ability to use the
            Service. See the Privacy Policy for details.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            10. Availability and changes to the service
          </h2>
          <p>
            The Service is offered on an ongoing but not guaranteed basis. We may
            add, change, suspend, or discontinue features, and we may perform
            maintenance that makes the Service temporarily unavailable. We will
            try to give reasonable notice of material changes that affect paid
            credits.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            11. Suspension and termination
          </h2>
          <p>
            You may stop using the Service and delete your account at any time
            from the account page. We may suspend or terminate access if you
            breach these terms, abuse the Service, or where required by law. If
            we terminate an account without cause,{" "}
            <Counsel>
              state whether and how unused purchased credits are refunded or
              credited in that case — this ties to the §4 refund decision.
            </Counsel>
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            12. Disclaimers
          </h2>
          <p>
            To the fullest extent permitted by law, the Service is provided
            &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without
            warranties of any kind, whether express or implied, including implied
            warranties of merchantability, fitness for a particular purpose,
            accuracy, and non-infringement. We do not warrant that the Service
            will be uninterrupted, error-free, or that the agent&rsquo;s output
            is accurate or reliable.{" "}
            <Counsel>
              confirm the exact warranty-disclaimer wording and any
              non-excludable statutory guarantees (e.g. UK/EU consumer rights,
              US state law) that cannot be disclaimed.
            </Counsel>
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            13. Limitation of liability
          </h2>
          <p>
            <Counsel>
              draft the limitation-of-liability clause and any cap (a common
              starting point ties the cap to amounts paid in the prior 12 months
              and excludes indirect/consequential damages), and confirm carve-outs
              for liability that cannot be limited by law (e.g. death/personal
              injury from negligence, fraud, consumer-law rights). This section
              is intentionally left for counsel rather than guessed.
            </Counsel>
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            14. Indemnification
          </h2>
          <p>
            <Counsel>
              decide whether to include a user-indemnification clause and, if so,
              its scope. For a small consumer service in some jurisdictions this
              is omitted or narrowed — a business/legal call.
            </Counsel>
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            15. Changes to these terms
          </h2>
          <p>
            We may update these terms as the Service changes. For material
            changes we will give notice by email to the address on your account
            and/or an in-app notice before the change takes effect, and we will
            update the &ldquo;Last updated&rdquo; date above. Continuing to use
            the Service after a change takes effect means you accept the updated
            terms.{" "}
            <Counsel>
              confirm the notice method and notice period, and whether material
              changes to paid terms require renewed opt-in.
            </Counsel>
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            16. Governing law and disputes
          </h2>
          <p>
            <Counsel>
              set the governing-law jurisdiction and dispute-resolution venue,
              and confirm they are compatible with mandatory local consumer
              protections for the regions you serve (EU/UK consumers generally
              keep the protections of their home country regardless of a
              choice-of-law clause).
            </Counsel>
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">
            17. Contact
          </h2>
          <p>
            Questions about these terms:{" "}
            <Counsel>
              legal entity name and postal address, and a contact email for
              legal/terms questions.
            </Counsel>
          </p>
        </section>
      </div>
    </article>
  );
}
