#!/usr/bin/env node
// Generate a subset of the tabler icon webfont containing ONLY the icons the
// app actually uses, plus a small stylesheet exposing them under the same
// `.ti ti-<name>` classes the components already use.
//
// Why: the full @tabler/icons-webfont stylesheet is ~211KB (38KB gzipped,
// 99.7% unused per Lighthouse) and chains a ~450KB woff2 — both render-
// blocking on every page, and the 2026-08 QA scan's worst performance cost.
// The app uses ~30 icons, so the subset font is a few KB.
//
// Outputs (BOTH COMMITTED, like the image variants):
//   public/fonts/tabler-icons-subset.woff2
//   app/icons.css   (imported by app/layout.tsx instead of the package CSS)
//
// Run `npm run icons:subset` after using a NEW ti-* icon anywhere in app/,
// components/, or lib/ — the script rescans the source for icon names. It is
// idempotent: unchanged inputs produce byte-identical outputs.

import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import subsetFont from "subset-font";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const pkgDir = path.join(root, "node_modules", "@tabler", "icons-webfont", "dist");

// ---- 1. Find every ti-* token used in the Next app's source. ----
// The lookbehind rejects prose hits like "multi-ref" / "anti-claim"; anything
// that still isn't a real icon name is dropped against the package's mapping.
const SRC_DIRS = ["app", "components", "lib"];
const TOKEN_RE = /(?<![a-z0-9])ti-[a-z0-9]+(?:-[a-z0-9]+)*/g;

function* sourceFiles(dir) {
  for (const name of readdirSync(dir)) {
    const p = path.join(dir, name);
    if (statSync(p).isDirectory()) yield* sourceFiles(p);
    else if (/\.(tsx?|css)$/.test(name)) yield p;
  }
}

const used = new Set();
for (const dir of SRC_DIRS) {
  for (const file of sourceFiles(path.join(root, dir))) {
    if (file.endsWith(path.join("app", "icons.css"))) continue; // our own output
    for (const m of readFileSync(file, "utf8").matchAll(TOKEN_RE)) used.add(m[0]);
  }
}

// ---- 2. Map names to codepoints from the package stylesheet. ----
const cssSrc = readFileSync(path.join(pkgDir, "tabler-icons.min.css"), "utf8");
const codepoints = new Map();
for (const m of cssSrc.matchAll(/\.ti-([a-z0-9-]+):before\{content:"\\([0-9a-f]+)"\}/g)) {
  codepoints.set(`ti-${m[1]}`, parseInt(m[2], 16));
}

const icons = [...used].filter((n) => codepoints.has(n)).sort();
const skipped = [...used].filter((n) => !codepoints.has(n)).sort();
if (skipped.length) console.log(`skipping non-icon tokens: ${skipped.join(", ")}`);
if (!icons.length) {
  console.error("no icons found — refusing to write an empty subset");
  process.exit(1);
}

// ---- 3. Subset the woff2 to those codepoints. ----
const fullFont = readFileSync(path.join(pkgDir, "fonts", "tabler-icons.woff2"));
const text = icons.map((n) => String.fromCodePoint(codepoints.get(n))).join("");
const subset = await subsetFont(fullFont, text, { targetFormat: "woff2" });

const fontDir = path.join(root, "public", "fonts");
mkdirSync(fontDir, { recursive: true });
const fontPath = path.join(fontDir, "tabler-icons-subset.woff2");
writeFileSync(fontPath, subset);

// ---- 4. Emit the stylesheet. ----
// The ?v= hash busts caches when the subset changes (public/ URLs aren't
// content-hashed by Next). font-display: block — icon glyphs are PUA
// codepoints, so swapping in a fallback font would flash tofu boxes.
const v = createHash("sha1").update(subset).digest("hex").slice(0, 8);
const rules = icons
  .map((n) => `.${n}:before { content: "\\${codepoints.get(n).toString(16)}"; }`)
  .join("\n");
const css = `/* GENERATED by scripts/icon-subset.mjs — do not edit by hand.
 * Subset of Tabler Icons (https://tabler.io, MIT) containing only the icons
 * this app uses. Re-run \`npm run icons:subset\` after adding a new ti-* icon.
 */
@font-face {
  font-family: "tabler-icons";
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url("/fonts/tabler-icons-subset.woff2?v=${v}") format("woff2");
}
.ti {
  font-family: "tabler-icons" !important;
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
${rules}
`;
writeFileSync(path.join(root, "app", "icons.css"), css);

console.log(
  `wrote ${icons.length}-icon subset: ${(subset.length / 1024).toFixed(1)}KB woff2 ` +
    `(full font ${(fullFont.length / 1024).toFixed(0)}KB), app/icons.css v=${v}`
);
